name: Extract Receipt Info with Qwen-VL

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/*.jpg'

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --no-cache-dir torch==2.2.0 torchvision==0.17.0 --index-url https://download.pytorch.org/whl/cpu
        pip install --no-cache-dir numpy==1.26.4 git+https://github.com/huggingface/transformers accelerate
        pip install --no-cache-dir pillow matplotlib tiktoken qwen-vl-utils


    - name: Run extraction script
      run: python extract_with_qwen.py

